comment: false
coverage:
  status:
    project: false
    patch:
      default:
        target: 40%
        threshold: 0%
        base: auto
        if_ci_failed: error
        if_not_found: success

fixes:
  - "/workspace/::"
