# Example configuration for pretraining a nanoGPT-style model on binary token shards
# produced by the `modded-nanogpt` preprocessing pipeline.

step_scheduler:
  grad_acc_steps: 16
  ckpt_every_steps: 2000
  num_epochs: 1

dist_env:
  backend: nccl
  timeout_minutes: 1

# Model
# Option 1 – shorthand builder
model:
  _target_: nemo_automodel.components.models.gpt2.build_gpt2_model
  vocab_size: 50258   # default 50257
  n_positions: 2048   # context length
  n_embd: 768         # hidden size
  n_layer: 12         # number of transformer blocks
  n_head: 12          # attention heads
  bos_token_id: 50256
  eos_token_id: 50256

# Option 2 – explicit HF config (uncomment to use)
# model:
#   _target_: nemo_automodel.NeMoAutoModelForCausalLM.from_config
#   config:
#     _target_: transformers.GPT2Config
#     vocab_size: 50258
#     n_positions: 2048
#     n_ctx: 2048
#     n_embd: 768
#     n_layer: 12
#     n_head: 12
#     bos_token_id: 50256
#     eos_token_id: 50256

# Dataset
# Point this to the location where your *.bin shards live.
# The pattern below matches the sample shards included in *modded-nanogpt*.
dataset:
  _target_: nemo_automodel.components.datasets.llm.nanogpt_dataset.NanogptDataset
  file_pattern: "modded-nanogpt/data/fineweb_10BT_max_500M/fineweb_train_*.bin"
  seq_len: 1024
  shuffle_files: true
  align_to_bos: false
  bos_token: 50256 # optional, only needed if align_to_bos is true

dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  batch_size: 8
  shuffle: false
  collate_fn: nemo_automodel.components.datasets.utils.default_collater

# Loss
loss_fn:
  _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy

# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 2.0e-4
  betas: [0.9, 0.95]
  weight_decay: 0.1

# DDP / FSDP2 / etc
distributed:
  _target_: nemo_automodel.components.distributed.fsdp2.FSDP2Manager
  dp_size: none
  tp_size: 1
  cp_size: 1
  sequence_parallel: false
